import type { Metadata } from "next";
import { Josefin_Sans, Indie_Flower } from "next/font/google";
import "./globals.css";
import ToastProvider from "./providers/ToastProvider";
import { AuthProvider } from "./providers/AuthProvider";
import BgLinear from "./component/BgLinear";
import ActiveStatus from "./component/ActiveStatus";

const fontBody = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

const fontTitle = Indie_Flower({
  variable: "--font-indie-flower",
  subsets:["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Create messenger App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${fontBody.variable} ${fontTitle.variable} antialiased`}
          >
            <AuthProvider>
              <ToastProvider />
              <BgLinear />
              <ActiveStatus />
              {children}
            </AuthProvider>
        </body>
      </html>
  );
}
